### ISSUE TITLE
피드 이미지 분석 

### ISSUE THREAD

**Issue by dahxxn** [comprehensive-design/style-scanner-backend#25]
#### 📍 이미지 검색/분석 툴 ? 
- [ ] Google Vision API 
- [ ] Naver Search API 
- [ ] Syte AI
- [ ] .... 

#### 📍 API 설계

**Comment by dahxxn** [comment]
피드 분석 어떻게 구현할지에 대해 서치하고 있는데 
기존에 나와있는 대부분의 Vision API는 이미지에서 객체 인식 정도만 하지 정확하게 상품 명에 대해서는 분석하지 못합니다. 

근데 dataset만 있으면 이중에서 어떤 이미지 속 상품과 유사하거나 동일한 것을 찾아주는 툴은 있는것 같은데 
저희 서비스는 도매 사이트가 아니기 때문에 dataset 이 없다 보니,,, 

그래서 패션/도매 dataset을 얻어오고 이를 dataset으로 해서 사용할 수 있는 상품 검색 api 툴을 찾아서 개발하는 것으로 방향을 잡아야 할 것 같아요 
+ 비즈니스 사용자가 아닌 일반 사용자도 사용할 수 있는 api/ai 툴로,,, 

위의 syte ai가 확실하게 저희가 원하는 기능을 수행하지만 비즈니스가 있어야지 사용할 수 있는 서비스여서 사용하기 좀 무리가 있는듯합니다요

**Comment by HyeonjunOh** [comment]
https://github.com/switchablenorms/DeepFashion2

이런 데이터셋이 있긴 한데
쓴다면 저희가 이거 써서 직접 학습시키는 건 불가능할 것 같고 아마 학습된 모델을 찾아 써야 할 것 같슴다

https://universe.roboflow.com/deepfashion-ut4u7/deepfashion-x9rga/model/1

찾아보니 이런 것도 있네요

저도 비전 api 좀 공부해보고 다른 방법도 있나 찾아보겠습니다

**Comment by dahxxn** [comment]
### 피드 분석 설계 1) OpenAI 사용  
1. 무신사, 29CM 데이터 크롤링 후 DB에 저장 
 - 상/하의 약 4만~5만장 수집
 - 상품 이미지, 링크, 상품명, 브랜드명, 가격, 상품 번호 , 태그 
2. 프론트로부터 받는 피드 이미지 Segmentation & Crop -> 실제 옷 착용 부분만 추출 및 확대
3. DB에 저장된 아이템 정보와 2에서 CROP한 옷 이미지와의 유사도를 CLIP 모델을 이용하여 임베딩 생성 
4. 두 임베딩의 유사도 계산 후 높은 순으로 상품 정렬하여 반환
